"""Replace MangaChapter f witholume

Revision ID: 40700da89cdd
Revises: 26dfabfd05ff
Create Date: 2026-02-01 21:30:36.077382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40700da89cdd'
down_revision = '26dfabfd05ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_volumes_chapter_id_chapters')),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], name=op.f('fk_volumes_manga_id_mangas')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('manga_chapters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_chapters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), nullable=True),
    sa.Column('manga_id', sa.INTEGER(), nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='fk_manga_chapters_chapter_id_chapters'),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], name='fk_manga_chapters_manga_id_mangas'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('volumes')
    # ### end Alembic commands ###
