"""initial schema

Revision ID: 64263640969b
Revises: 
Create Date: 2025-12-22 03:45:03.675032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64263640969b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mangas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_manga_chapters_chapter_id_chapters')),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], name=op.f('fk_manga_chapters_manga_id_mangas')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], name=op.f('fk_reviews_manga_id_mangas')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('manga_chapters')
    op.drop_table('mangas')
    op.drop_table('chapters')
    # ### end Alembic commands ###
