"""switch join table Chapter to Volume

Revision ID: b43146501782
Revises: 40700da89cdd
Create Date: 2026-02-06 23:09:44.050141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43146501782'
down_revision = '40700da89cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('volume_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chapters_manga_id_mangas'), 'mangas', ['manga_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_chapters_volume_id_volumes'), 'volumes', ['volume_id'], ['id'])

    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volumes_manga_id_mangas', type_='foreignkey')
        batch_op.drop_constraint('fk_volumes_chapter_id_chapters', type_='foreignkey')
        batch_op.drop_column('chapter_id')
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('chapter_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_volumes_chapter_id_chapters', 'chapters', ['chapter_id'], ['id'])
        batch_op.create_foreign_key('fk_volumes_manga_id_mangas', 'mangas', ['manga_id'], ['id'])

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chapters_volume_id_volumes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_chapters_manga_id_mangas'), type_='foreignkey')
        batch_op.drop_column('volume_id')
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###
